// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "surfaceplotctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CSurfacePlot

IMPLEMENT_DYNCREATE(CSurfacePlot, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSurfacePlot properties

double CSurfacePlot::GetDistance()
{
	double result;
	GetProperty(0x1, VT_R8, (void*)&result);
	return result;
}

void CSurfacePlot::SetDistance(double propVal)
{
	SetProperty(0x1, VT_R8, propVal);
}

double CSurfacePlot::GetVerticalAngle()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CSurfacePlot::SetVerticalAngle(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

double CSurfacePlot::GetAzimuth()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CSurfacePlot::SetAzimuth(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

BOOL CSurfacePlot::GetHideLines()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CSurfacePlot::SetHideLines(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSurfacePlot operations

void CSurfacePlot::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
