#if !defined(AFX_SURFACEPLOTCTRL_H__E4A21EF4_3C5F_4968_8451_2A635DB8BC49__INCLUDED_)
#define AFX_SURFACEPLOTCTRL_H__E4A21EF4_3C5F_4968_8451_2A635DB8BC49__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSurfacePlot wrapper class

class CSurfacePlot : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSurfacePlot)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7e0d9edc, 0x75a, 0x11d2, { 0x91, 0x4a, 0x0, 0xc0, 0xdf, 0xe5, 0x28, 0x74 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	double GetDistance();
	void SetDistance(double);
	double GetVerticalAngle();
	void SetVerticalAngle(double);
	double GetAzimuth();
	void SetAzimuth(double);
	BOOL GetHideLines();
	void SetHideLines(BOOL);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SURFACEPLOTCTRL_H__E4A21EF4_3C5F_4968_8451_2A635DB8BC49__INCLUDED_)
