// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPrikazRasporedaIspita wrapper class

class CPrikazRasporedaIspita : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPrikazRasporedaIspita)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x58e19248, 0xa94f, 0x4762, { 0xb5, 0x43, 0xf, 0x1c, 0xd6, 0xc3, 0xb7, 0x1d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetItemNameLengthPercentage();
	void SetItemNameLengthPercentage(short);
	short GetAdditionalDataLengthPercentage();
	void SetAdditionalDataLengthPercentage(short);

// Operations
public:
	BOOL AddRow(LPCTSTR ItemName);
	BOOL AddRowTerm(short RowNum, short Term);
	BOOL MoveUp();
	BOOL MoveDown();
	short GetRowNum();
	short GetItemNum();
	void AboutBox();
};
