// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "testcontrolempty.h"

/////////////////////////////////////////////////////////////////////////////
// CTestControlEmpty

IMPLEMENT_DYNCREATE(CTestControlEmpty, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTestControlEmpty properties

/////////////////////////////////////////////////////////////////////////////
// CTestControlEmpty operations

void CTestControlEmpty::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
