#if !defined(AFX_UPDOWN_H__19A7B307_6B41_11D3_A9B0_00C0DFE5278A__INCLUDED_)
#define AFX_UPDOWN_H__19A7B307_6B41_11D3_A9B0_00C0DFE5278A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CUpDown wrapper class

class CUpDown : public CWnd
{
protected:
	DECLARE_DYNCREATE(CUpDown)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x603c7e80, 0x87c2, 0x11d1, { 0x8b, 0xe3, 0x0, 0x0, 0xf8, 0x75, 0x4d, 0xa1 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetValue(long nNewValue);
	long GetValue();
	void SetAlignment(long nNewValue);
	long GetAlignment();
	void SetAutoBuddy(BOOL bNewValue);
	BOOL GetAutoBuddy();
	void SetBuddyControl(const VARIANT& newValue);
	void SetRefBuddyControl(const VARIANT& newValue);
	VARIANT GetBuddyControl();
	void SetIncrement(long nNewValue);
	long GetIncrement();
	void SetMax(long nNewValue);
	long GetMax();
	void SetMin(long nNewValue);
	long GetMin();
	void SetOrientation(long nNewValue);
	long GetOrientation();
	void SetSyncBuddy(BOOL bNewValue);
	BOOL GetSyncBuddy();
	void SetWrap(BOOL bNewValue);
	BOOL GetWrap();
	void SetBuddyProperty(const VARIANT& newValue);
	VARIANT GetBuddyProperty();
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	long GetHWnd();
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	void OLEDrag();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_UPDOWN_H__19A7B307_6B41_11D3_A9B0_00C0DFE5278A__INCLUDED_)
