//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QAPSolver.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_QAPSOLTYPE                  129
#define IDD_VIEW_DATA                   130
#define IDD_OPTIMIZATION_GENETIC        132
#define IDD_OPTIMIZATION_TABU_SEARCH    134
#define IDD_OPTIMIZATION_SIM_ANNEALING  136
#define IDD_VIEW_RESULTS                138
#define IDD_VIEW_GRAPH_RESULTS          140
#define IDD_SELECT_GRAPH_DLG            142
#define IDD_VIEW_BEST_SOLUTION          143
#define IDD_TEST_3DCHART                144
#define IDR_MENU1                       147
#define IDD_GENERIC_ITERATIVE_OPT       149
#define IDD_SET_INSTANCES               151
#define IDD_OPT_COMPARE_SAME            152
#define IDD_ALG_DEPENDENCE_TIME         152
#define IDD_ALG_DEPENDENCE_QUALITY      156
#define IDR_QAP_COMPARETYPE             157
#define IDC_MATRIX_A                    1000
#define IDC_MATRIX_B                    1001
#define IDC_SOLUTION                    1002
#define IDC_CMD_START                   1009
#define IDC_CMD_STOP                    1010
#define IDC_EDIT_MUT_PROB               1014
#define IDC_EDIT_POP_SIZE               1015
#define IDC_EDIT_ITER_NUM               1017
#define IDC_EDIT_CALLBACK_PERIOD        1019
#define IDC_CMD_CONTINUE                1020
#define IDC_CMD_USE_NEW_PARAM           1021
#define IDC_SPIN_CALLBACK_PERIOD        1022
#define IDC_EDIT_TABU_LIST_SIZE         1022
#define IDC_CMD_USE_NEW_PARAMETERS      1026
#define IDC_EDIT_ACCEPT_HIGHER_PROB     1032
#define IDC_EDIT_TEMP_CHANGE_FACTOR     1033
#define IDC_INFO_MAX_VALUE              1039
#define IDC_INFO_CURR_VALUE             1040
#define IDC_INFO_MAX_SOL                1041
#define IDC_INFO_CURR_SOL               1042
#define IDC_INFO_DURATION               1043
#define IDC_INFO_ITER_NUM               1044
#define IDC_RESULTS                     1047
#define IDC_SHOW_IN_SAME                1049
#define IDC_DRAW_METAFILE               1051
#define IDC_CTRL_GRAPH                  1052
#define IDC_DELETE_OPT_RES_CMD          1053
#define IDC_EDIT_GRAPH_NUM              1055
#define IDC_EDIT_SAVE_RESULTS_PERIOD    1056
#define IDC_EDIT_PERM_NUM               1057
#define IDC_EDIT_VALUE                  1058
#define IDC_EDIT_ASSIGNMENT             1059
#define IDC_CHECK_USE_COLORS            1062
#define IDC_CHECK_USE_LINESTYLES        1063
#define IDC_CHART                       1064
#define IDC_CHECK_ITER_NUM              1065
#define IDC_CHECK_OPTIM_DURATION        1066
#define IDC_CHECK_REACHED_VALUE         1067
#define IDC_EDIT_OPTIM_DURATION         1068
#define IDC_EDIT_REACHED_VALUE          1069
#define IDC_EDIT_FILENAME               1070
#define IDC_EDIT_FILENAME1              1070
#define IDC_EDIT_FILENAME2              1071
#define IDC_EDIT_FILENAME3              1072
#define IDC_EDIT_FILENAME4              1073
#define IDC_EDIT_FILENAME5              1074
#define IDC_EDIT_FILENAME6              1075
#define IDC_EDIT_FILENAME7              1076
#define IDC_EDIT_FILENAME8              1077
#define IDC_EDIT_FILENAME9              1078
#define IDC_EDIT_FILENAME10             1079
#define IDC_BROWSE_CMD                  1080
#define IDC_BROWSE_CMD1                 1080
#define IDC_BROWSE_CMD2                 1081
#define IDC_BROWSE_CMD3                 1082
#define IDC_BROWSE_CMD4                 1083
#define IDC_BROWSE_CMD5                 1084
#define IDC_BROWSE_CMD6                 1085
#define IDC_BROWSE_CMD7                 1086
#define IDC_BROWSE_CMD8                 1087
#define IDC_BROWSE_CMD9                 1088
#define IDC_BROWSE_CMD10                1089
#define IDC_LIST                        1091
#define IDC_ADD_CMD                     1092
#define IDC_DELETE_CMD                  1093
#define IDC_COMBO1                      1094
#define IDC_ALG_TYPE                    1094
#define IDC_EDIT1                       1095
#define IDC_PAR_VALUES1                 1095
#define IDC_EDIT2                       1096
#define IDC_PAR_VALUES2                 1096
#define IDC_EDIT3                       1097
#define IDC_PAR_VALUES3                 1097
#define IDC_EDIT4                       1098
#define IDC_PAR_VALUES4                 1098
#define IDC_PARNAME1                    1099
#define IDC_PARNAME2                    1100
#define IDC_PARNAME3                    1101
#define IDC_PARNAME4                    1102
#define IDC_START_CMD                   1103
#define IDC_STOP_CMD                    1104
#define IDC_CONTINUE_CMD                1105
#define IDC_CHECK_CALLBACK_ITERNUM      1106
#define IDC_CHECK_CALLBACK_EVERY_IMPROVEMENT 1107
#define IDC_CMD_PERFORM_INITAL          1108
#define IDC_CHECK_CALLBACK_MILISEC      1109
#define IDC_CHECK_SAVE_ITERNUM          1110
#define IDC_CHECK_SAVE_EVERY_IMPROVEMENT 1111
#define IDC_CHECK_SAVE_MILISEC          1112
#define IDC_EDIT_TERM_ITER_NUM          1113
#define IDC_EDIT_TERM_OPTIM_DURATION    1114
#define IDC_EDIT_TERM_REACHED_VALUE     1115
#define IDC_EDIT_CALLBACK_ITERNUM       1116
#define IDC_EDIT_CALLBACK_MILISEC       1117
#define IDC_CHECK_TERM_ITER_NUM         1118
#define IDC_CHECK_TERM_OPTIM_DURATION   1119
#define IDC_CHECK_TERM_REACHED_VALUE    1120
#define IDC_EDIT_SAVE_ITERNUM           1121
#define IDC_EDIT_SAVE_MILISEC           1122
#define IDC_RANGE_FROM1                 1124
#define IDC_RANGE_TO1                   1125
#define IDC_RANGE_STEP1                 1126
#define IDC_RANGE_FROM2                 1127
#define IDC_RANGE_TO2                   1128
#define IDC_RANGE_STEP2                 1129
#define IDC_RANGE_FROM3                 1130
#define IDC_RANGE_TO3                   1131
#define IDC_RANGE_STEP3                 1132
#define IDC_RANGE_FROM4                 1133
#define IDC_RANGE_TO4                   1134
#define IDC_RANGE_STEP4                 1135
#define IDC_PROGRESS                    1136
#define IDC_REPETITION_NUM              1137
#define IDC_SOL_VALUE1                  1139
#define IDC_STATIC1                     1140
#define IDC_STATIC2                     1141
#define IDC_STATIC3                     1142
#define IDC_STATIC4                     1143
#define IDC_STATIC5                     1144
#define IDC_STATIC6                     1145
#define IDC_STATIC7                     1146
#define IDC_STATIC8                     1147
#define IDC_STATIC9                     1148
#define IDC_STATIC10                    1149
#define IDC_SET_BEST_SOL_CMD            1150
#define IDC_SOL_VALUE2                  1151
#define IDC_SOL_VALUE3                  1152
#define IDC_SOL_VALUE4                  1153
#define IDC_SOL_VALUE5                  1154
#define IDC_SOL_VALUE6                  1155
#define IDC_SOL_VALUE7                  1156
#define IDC_LOAD_BESTSOL_CMD            1158
#define IDC_SOL_VALUE8                  1159
#define IDC_SOL_VALUE9                  1160
#define IDC_SOL_VALUE10                 1161
#define IDC_LOAD_BESTSOL_CMD2           1168
#define IDC_LOAD_BESTSOL_CMD3           1169
#define IDC_LOAD_BESTSOL_CMD4           1170
#define IDC_LOAD_BESTSOL_CMD5           1171
#define IDC_LOAD_BESTSOL_CMD6           1172
#define IDC_LOAD_BESTSOL_CMD7           1173
#define IDC_LOAD_BESTSOL_CMD8           1174
#define IDC_LOAD_BESTSOL_CMD9           1175
#define IDC_LOAD_BESTSOL_CMD10          1176
#define ID_FILE_LOAD_PROBLEM_DATA       32771
#define ID_VIEW_DATA                    32772
#define ID_START_OPTIMIZATION_GENETIC   32774
#define ID_START_OPTIMIZATION_SIMANN    32778
#define ID_VIEW_RESULTS                 32779
#define ID_FILE_LOAD_BEST_SOL           32780
#define ID_VIEW_BEST_SOLUTION           32781
#define ID_TABU_SEARCH_SIMPLE           32782
#define ID_TABU_SEARCH_ROBUST           32783
#define ID_TABU_SEARCH_SIMPLE_DIVERSIFY 32783
#define ID_OPT_COMPARE_DIFF_PAR         32784
#define ID_TABU_SEARCH_ROBUST_SIMPLE    32785
#define ID_COMPARE_TIME_TO_REACH_SOLUTION 32788
#define ID_COMPARE_QUALITY_AFTER_ITER_NUM 32789
#define ID_COMPARE_QUALITY_AFTER_TIME   32790
#define ID_COMPARE_TIME_BEST_SOLUTION   32791
#define ID_COMPARE_DIFF_PAR_TS_SIMPLE   32792
#define ID_ALG_DEPENDENCE_TIME_TO_REACH 32792
#define ID_TEST_CHART                   32793
#define IDC_MENU_VIEW_SOLUTION          32794
#define IDC_MENU_SHOW_GRAPH             32795
#define ID_START_OPTIMIZATION_GRASP     32796
#define ID_OPTIONS_SET_INSTANCES        32797
#define ID_VIEW_COMPARABLE_RESULTS      32798
#define ID_OPTIMIZATION_STARTCOMPARISONOPTIMIZATIONALGORITHMDEPENDENCEONPARAMETERS 32799
#define ID_TEST_GENERIC                 32800
#define ID_TABU_SEARCH_ROBUST_DIVERSIFY 32801
#define ID_TABU_SEARCH_REACTIVE2        32802
#define ID_ALG_DEPENDENCE_QUALITY       32803
#define ID_VIEW_ALGORITHMDEPENDENCEONPARAMETERS_TIME 32804
#define ID_VIEW_ALGORITHMDEPENDENCEONPARAMETERS_QUALITY 32805
#define ID_FILE_SET_PROBLEM_INSTANCES   32806
#define ID_ALG_DEPENDENCE_TIME          32807
#define ID_START_OPTIMIZATION_BR_SIMANN 32809
#define ID_START_OPTIMIZATION_WW_SIMANN 32810
#define ID_START_OPTIMIZATION_CONNOLY_SIMANN 32811
#define ID_START_OPTIMIZATION_AUT_CONNOLY_SIMANN 32812
#define ID_START_OPTIMIZATION_AUT_SIMANN 32814
#define ID_START_OPTIMIZATION_3TOUR_SELECTION 32815
#define ID_START_OPTIMIZATION_GREEDY_GA 32816
#define ID_START_OPTIMIZATION_FFGA      32817
#define ID_START_OPTIMIZATION_FIRST_IMPROV 32819
#define ID_START_OPTIMIZATION_BEST_IMPROV 32820
#define ID_START_OPTIMIZATION_HEIDER    32821
#define ID_COMPARE_TABU_SEARCH          32822
#define ID_COMPARE_GENETIC              32823
#define ID_COMPARE_SIM_ANN              32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1159
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
