//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dialog2.rc
//
#define IDD_WNDSIZE                     101
#define IDD_ABOUTBOX                    102
#define IDD_DIALOG1                     103
#define IDD_DLGBAR                      103
#define IDD_DIALOG2                     104
#define IDD_DIALOG_FIKS                 105
#define IDD_DATUM_FIKS                  105
#define IDI_ICON_GA                     116
#define IDD_KOLEGIJ                     119
#define IDD_PARAMETRI                   120
#define IDD_DIALOG_PODACI               122
#define IDI_ICON1                       123
#define IDI_ICON5                       127
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR1                    128
#define IDD_DIALOG_GRESKA               131
#define IDI_ICON2                       133
#define IDD_DIALOG_GRESKA_2             134
#define IDI_ICON3                       135
#define IDD_UCIT_MASOVNI                137
#define IDD_DIALOG_NAPREDAK             138
#define IDI_ICON4                       139
#define IDD_DIALOG_GRESKA_3             140
#define IDC_RADIO_320                   1000
#define IDC_RADIO_640                   1001
#define IDC_RADIO_800                   1002
#define IDC_EDIT1                       1002
#define IDC_RADIO_1024                  1003
#define IDC_EDIT5                       1003
#define IDC_RADIO_DESKTOP               1004
#define IDC_EDIT6                       1004
#define IDC_EDIT_WIDTH                  1006
#define IDC_EDIT_HEIGHT                 1007
#define IDC_RADIO_CUSTOM                1008
#define IDC_STATIC_WIDTH                1009
#define IDC_STATIC_HEIGHT               1010
#define IDC_EDIT2                       1014
#define IDC_SPIN3                       1015
#define IDC_EDIT7                       1015
#define IDC_EDIT3                       1016
#define IDC_EDIT8                       1016
#define IDC_SPIN4                       1017
#define IDC_EDIT10                      1017
#define IDC_BUTTON1                     1021
#define IDC_BUTTON_NASTAV_PLAN          1021
#define IDC_EDIT_ROK_1                  1022
#define IDC_EDIT_ROK_2                  1023
#define IDC_EDIT_ROK_3                  1024
#define IDC_EDIT_SIFRA                  1025
#define IDC_EDIT_ZAPORKA                1025
#define IDC_EDIT_NAZIV                  1026
#define IDC_PROGRESS1                   1032
#define IDC_PROGRESS2                   1033
#define IDC_LIST1                       1034
#define IDC_LIST_KOLEGIJI               1034
#define IDC_EDIT4                       1035
#define IDC_LIST_KOLEGIJI_FIKS          1035
#define IDC_BUTTON_POBRISI              1038
#define IDC_BUTTON_DATUM                1039
#define IDC_BUTTON_PRIJENOS             1040
#define IDC_SPIN1                       1041
#define IDC_SPIN2                       1042
#define IDC_SPIN5                       1043
#define IDC_SPIN7                       1045
#define IDC_SPIN8                       1046
#define IDC_SPIN9                       1047
#define IDC_SPIN10                      1048
#define IDC_EDIT9                       1049
#define IDC_SPIN11                      1050
#define IDC_SPIN12                      1051
#define IDC_BUTTON_OPEN                 1052
#define IDC_RADIO_GOD_1                 1053
#define IDC_RADIO_GOD_2                 1054
#define IDC_RADIO_GOD_3                 1055
#define IDC_RADIO_GOD_4                 1056
#define IDC_EDIT11                      1057
#define IDC_SPIN6                       1058
#define IDC_EDIT15                      1066
#define IDC_SPIN16                      1067
#define IDC_EDIT17                      1071
#define IDC_SPIN18                      1072
#define IDC_RADIO_ROK_Z                 1073
#define IDC_RADIO_ROK_P                 1074
#define IDC_RADIO_ROK_LJ                1075
#define IDC_RADIO_ROK_J                 1076
#define IDC_EDIT_DG                     1077
#define IDC_SPIN13                      1078
#define IDC_EDIT_IG                     1079
#define IDC_EDIT_GG                     1080
#define IDC_SPIN14                      1081
#define IDC_BUTTON_PRESJEK              1082
#define IDC_PROGRESS3                   1083
#define IDC_EDIT12                      1086
#define IDC_SPIN15                      1087
#define ID_FILE_EXIT                    32775
#define ID_BUTTON_GA                    40001
#define ID_BUTTON_FX                    40003
#define ID_HELP_ABOUT                   40008
#define ID_DIALOG_WNDSIZE               40009
#define ID_OPCIJE_PARAMETRIOPTIMIZACIJE 40010
#define ID_OPCIJE_PREDODREENIDATUMI     40011
#define ID_DATOTEKA_UCITAVANJEPODATAKA  40012
#define ID_DATOTEKA_SNIMANJEREZULTATA   40013
#define ID_DATOTEKA_SNIMANJEODABRANOGREZULTATA 40014
#define ID_BUTTON_OPEN                  40015
#define ID_BUTTON_SAVE                  40016
#define ID_BUTTON_OPCIJE                40017
#define ID_BUTTON_ABOUT                 40019
#define ID_BUTTON_SAVE_TREN             40022
#define ID_BUTTON_STOP                  40026
#define ID_ALATI_POKRENIOPTIMIZACIJU    40030
#define ID_BUTTON40033                  40033
#define ID_ALATI_ZAUSTAVLJANJEOPTIMIZACIJE 40034
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40035
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
